- hosts: all
  roles:
    - common

- hosts: workspace
  roles:
    - app
    - composer
    - docker
    - docker-compose
    - httpd
    - mariadb
    - php
    - php-fpm
    - phpstorm
    - sqlite
