- name: Check if PhpStorm is already installed
  stat:
    path: "{{ phpstorm_bin }}"
  register: __phpstorm_bin
  tags:
    - phpstorm

- name: Download PhpStorm archive
  get_url:
    url: https://download.jetbrains.com/webide/PhpStorm-2019.2.1.tar.gz
    dest: /tmp/phpstorm.tar.gz
    checksum: "sha256:4f102a1dcfad15d27b0674465bf5f5cd628388ee98bf5c0d64be1954cc4529d4"
  when: not __phpstorm_bin.stat.exists
  tags:
    - phpstorm

- name: Ensure /opt/phpstorm folder exists
  file:
    path: /opt/phpstorm
    state: directory
  tags:
    - phpstorm
  become: true

- name: Extract PhpStorm archive
  unarchive:
    src: /tmp/phpstorm.tar.gz
    dest: "{{ phpstorm_path }}"
    remote_src: yes
  when: not __phpstorm_bin.stat.exists
  tags:
    - phpstorm
  become: true

- name: Remove PhpStorm archive
  file:
    path: /tmp/phpstorm.tar.gz
    state: absent
  tags:
    - phpstorm

- name: Copy menu launcher
  copy:
    src: jetbrains-phpstorm.desktop
    dest: "{{ home_directory }}/.local/share/applications/"
  tags:
    - phpstorm
