- name: Check if PhpStorm is already installed
  stat:
    path: "{{ phpstorm_bin }}"
  register: __phpstorm_bin
  tags:
    - phpstorm

- name: Download PhpStorm archive
  get_url:
    url: https://download.jetbrains.com/webide/PhpStorm-2019.2.tar.gz
    dest: /tmp/phpstorm.tar.gz
    checksum: "sha256:a7b81953467fc1c1b3f270bd905018b40243d9f2aeb11b70e648489b843db84f"
  when: not __phpstorm_bin.stat.exists
  tags:
    - phpstorm

- name: Ensure /opt/phpstorm folder exists
  file:
    path: /opt/phpstorm
    state: directory
  tags:
    - phpstorm
  become: true

- name: Extract PhpStorm archive
  unarchive:
    src: /tmp/phpstorm.tar.gz
    dest: "{{ phpstorm_path }}"
    remote_src: yes
  when: not __phpstorm_bin.stat.exists
  tags:
    - phpstorm
  become: true

- name: Remove PhpStorm archive
  file:
    path: /tmp/phpstorm.tar.gz
    state: absent
  tags:
    - phpstorm

- name: Copy menu launcher
  copy:
    src: jetbrains-phpstorm.desktop
    dest: "{{ home_directory }}/.local/share/applications/"
  tags:
    - phpstorm
