- name: Install MariaDB packages
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - mariadb-server
  tags:
    - mariadb
  become: true

- name: Enable and start MariaDB service
  systemd:
    name: mariadb
    enabled: yes
    masked: no
    state: started
  tags:
    - mariadb
  become: true
