- name: Install httpd packages
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - httpd
    - mod_ssl
  tags:
    - httpd
  become: true

- name: Enable and start httpd service
  systemd:
    name: httpd
    enabled: yes
    masked: no
    state: started
  tags:
    - httpd
  become: true
