- name: Register user home directory
  command: echo ~
  register: home_directory
  tags:
    - always

- name: Store user home directory globally
  set_fact:
    home_directory: "{{ home_directory.stdout }}"
  tags:
    - always

- name: Enable contrib repository
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
  become: true

- name: Install common packages
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - curl
    - git
    - nano
    - rsync
    - unzip
    - wget
  become: true
