- name: Enable amazon-linux-extras packages
  shell: amazon-linux-extras enable {{ item }}
  with_items:
    - httpd_modules
    - lamp-mariadb10.2-php7.2
    - php7.2
  become: true

- name: Install common packages
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - curl
    - git
    - nano
    - rsync
    - unzip
    - wget
  become: true
